export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
// AJAX
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_PIPE_SUCCESS = 'CREATE_PIPE_SUCCESS';
export const UPDATE_PIPE_SUCCESS = 'UPDATE_PIPE_SUCCESS';
export const LOAD_PIPE_SUCCESS = 'LOAD_PIPE_SUCCESS';



